name: custom_io
description: A Simple I/O Package for Code reusablity.
version: 1.0.6
homepage: https://github.com/Shanu33/Dart-Custom-IO
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
